#!/usr/local/bin/expect
set hn [exec hostname]
puts "executing NetgbTom $hn"
log_user 0
spawn NetgbTom $hn
expect eof
log_user 1
spawn emacs -nw
expect "Ready for Emacs (Version 18)."
send "\033xgdb\r"
expect "Run gdb on file:*tierra/"
send "tierra-Mon-Stdio\r"
expect "(gdb)"
while (1) {
interact {
  "\007" break
}
}
send "\r"
expect "(gdb)"
send "run siTom-$hn > /dev/null\r"
interact

